### ISSUE TITLE
Can't fake a module more than once during tests & issues faking module that other modules depend on

### ISSUE THREAD

**Issue by InvigoDev** [adonisjs/fold#50]
Hello, we are having some issues with faking a module in multiple tests. The faked version of the module is being carried over between tests. When a module depends on the 'faked' module, it will only use the first faked version that appears in all of the tests. More below.

## Package version
4.0.9

## Node.js and npm version
Node v12.5.0 & npm v6.9.0

## Sample Code (to reproduce the issue)
A.JS
console.log('getting b')
const b = use('b')
module.exports = function() {
  return b()
}
____
B.JS
module.exports = function() {
  return 'real'
}
____
TEST.SPEC.JS
const { test, trait } = use('Test/Suite')('Post')
// ioc(inversion of control) is used to 'fake' methods for testing purposes
const { ioc } = use('@adonisjs/fold')
trait('Test/ApiClient')

test('If we can reproduce the bug', () => {
  ioc.fake('b', () => {
    return function() {
      return 'fake'
    }
  })
  const a = use('a')
  console.log(a())
  ioc.restore('b')
  ioc.fake('b', () => {
    return function() {
      return 'super fake'
    }
  })
  console.log(a())
  ioc.restore('b')
})
____

OUTPUT AFTER RUNNING ADONIS TEST:
getting b
fake
fake
    ✓ If we can reproduce the bug (38ms)

_______
DESCRIPTION: 

We are having issues when it comes to faking modules for testing. When we fake a module that other modules depend on ('b' in the example), then once we call 'use' on the module that depends on it ('a' in the example), the module will load the 'faked' version. However, after restoring, and in a totally different test, the module ended up still using the 'faked' version of the module it depends on!('a' still had a faked 'b' even with a seperate 'use' call).

We noticed it is because nodejs's require.cache still recalls the previous 'required' version of a(the one which had the faked module b) and does not attempt to load it again to see the changes. As you can see in the example above, it only printed 'getting b' once even though there were more than 1 calls of "use('a')".

We can solve this by invalidating the cache(emptying it of the instance of a) but this is very messy as our actual code is much more complex and has many classes being loaded up. We'd have to know beforehand which classes were loaded involving the module we want to fake and remove them from the cache between tests.

Is there a solution using fold for this issue? What would you recommend we do to solve this issue?

Thanks,
Invigo

**Comment by KevinCepria** [comment]
Having the same issue @InvigoDev is experiencing. Any fix on this?

**Comment by thetutlage** [comment]
Fixed in v5. Unfortunately, backporting the fix is not possible without any breaking changes

**Comment by mortocks** [comment]
@InvigoDev any chance you can post an example of how you're invalidating the require.cache as a workaround to this problem?
