### ISSUE TITLE
Fake in test bleeds over to other tests

### ISSUE THREAD

**Issue by chadhobson** [adonisjs/fold#51]
## Package version
5.09

## Node.js and npm version
Node: 11.13.0
NPM: 6.7.0

## Sample Code (to reproduce the issue)
See foo-test.spec.js in repo

## BONUS (a sample repo to reproduce the issue)
https://github.com/chadhobson/AdonisFakeFailsTest

**Comment by hugobessa** [comment]
Is there a workaround for this on v4?

**Comment by thetutlage** [comment]
@hugobessa Unfortunately not, coz of the way the IoC container was designed. Changing the design means introducing breaking changes and we did that with v5.
