### ISSUE TITLE
Add Typescript support

### ISSUE THREAD

**Issue by comatory** [adonisjs/fold#53]
## Why this feature is required (specific use-cases will be appreciated)?

When using Typescript in strict mode, the code will not compile because TS definitions are not present.

## Have you tried any other work arounds?

I have tried looking up definitions in `DefinitelyTyped` repository but it's not there.

## Are you willing to work on it with little guidance?

Maybe.

**Comment by thetutlage** [comment]
The source code is written in typescript. So I am not sure why separate typings are required?

**Comment by comatory** [comment]
@thetutlage Ok. I am unsure if I'm installing `@adonisjs/fold` package correctly then. When I do `npm i @adonisjs/fold`, version `4.0.9` gets installed. That version is written in JavaScript thus TSC complains about missing definitions.

**Comment by thetutlage** [comment]
Are you using it with Adonisjs or outside of it?

**Comment by comatory** [comment]
I’m using it as a standalone package.

**Comment by thetutlage** [comment]
Okay, then I suggest installing with `@alpha` tag.

```
npm i @adonisjs/fold@alpha
```

This gives you the latest version

**Comment by thetutlage** [comment]
Also don't get tripped with the `@alpha` tag. This is mainly relevant for AdonisJS. The package itself is stable

**Comment by comatory** [comment]
So is there a reason why NPM default version is not the newer one? It’s not considered stable?

**Comment by thetutlage** [comment]
The default version is used by many of the AdonisJS v4 apps in production. The `@alpha` version is targeting v5 of the framework and is a complete rewrite. 

I do not want to break existing v4 applications. So thats why published it under a different tag.
